# 3. NumPy Shape Manipulation

In [1]:
import numpy as np

In [3]:
# Shape Manipulation

A = np.floor(np.random.random((3,4)) * 10)
print("A is : \n"+str(A))

print("Flattened A is : \n"+str(A.flatten()))

print("Reshaped A is : \n"+str(A.reshape(4,3)))

print("Transposed A is : \n"+str(A.T))

A.resize(6,2) # Resize will affect the original array while using reshape create a new reshaped instance of the array.
print("Resized A is : \n"+str(A))  

print("Reshaped A is : \n"+str(A.reshape(-1,4)))  #If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated

A is : 
[[3. 8. 9. 3.]
 [2. 9. 9. 9.]
 [6. 2. 9. 5.]]
Flattened A is : 
[3. 8. 9. 3. 2. 9. 9. 9. 6. 2. 9. 5.]
Reshaped A is : 
[[3. 8. 9.]
 [3. 2. 9.]
 [9. 9. 6.]
 [2. 9. 5.]]
Transposed A is : 
[[3. 2. 6.]
 [8. 9. 2.]
 [9. 9. 9.]
 [3. 9. 5.]]
Resized A is : 
[[3. 8.]
 [9. 3.]
 [2. 9.]
 [9. 9.]
 [6. 2.]
 [9. 5.]]
Reshaped A is : 
[[3. 8. 9. 3.]
 [2. 9. 9. 9.]
 [6. 2. 9. 5.]]


In [28]:
# Stack arrays

B = np.floor(np.random.random((3,2)) * 10)
print("A is : \n"+str(A))
print("B is : \n"+str(B))


print("Vertical stack of A and B is : \n"+str(np.vstack((A,B))))

C = np.floor(np.random.random((3,6)) *10)

print("C is : \n"+str(C))

print("Horizontal stack of B and C is : \n"+str(np.hstack((B,C))))



A is : 
[[3. 8.]
 [9. 3.]
 [2. 9.]
 [9. 9.]
 [6. 2.]
 [9. 5.]]
B is : 
[[7. 6.]
 [2. 4.]
 [1. 0.]]
Vertical stack of A and B is : 
[[3. 8.]
 [9. 3.]
 [2. 9.]
 [9. 9.]
 [6. 2.]
 [9. 5.]
 [7. 6.]
 [2. 4.]
 [1. 0.]]
C is : 
[[9. 1. 0. 5. 4. 1.]
 [6. 1. 1. 6. 7. 6.]
 [2. 9. 4. 1. 9. 0.]]
Horizontal stack of B and C is : 
[[7. 6. 9. 1. 0. 5. 4. 1.]
 [2. 4. 6. 1. 1. 6. 7. 6.]
 [1. 0. 2. 9. 4. 1. 9. 0.]]


array([[4, 6],
       [2, 8]])

In [33]:
# column_stack and row_stack
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

print("Horizontal stack of B and C is : \n"+str(np.hstack((B,C))))
print("Column Stack of B and C is : \n"+str(np.column_stack((B, C))))

D = np.array([4,2])
E = np.array([6,8])

np.column_stack((D,E))


from numpy import newaxis
D[:,newaxis]

Horizontal stack of B and C is : 
[[7. 6. 9. 1. 0. 5. 4. 1.]
 [2. 4. 6. 1. 1. 6. 7. 6.]
 [1. 0. 2. 9. 4. 1. 9. 0.]]
Column Stack of B and C is : 
[[7. 6. 9. 1. 0. 5. 4. 1.]
 [2. 4. 6. 1. 1. 6. 7. 6.]
 [1. 0. 2. 9. 4. 1. 9. 0.]]


array([[6, 8]])

In [46]:
# Split Arrays

F = np.floor(np.random.random((2,12)) * 100)
print("F is : \n"+str(F))

print("Horizontally Splitted in 3 : \n"+str(np.hsplit(F,3)))


print("Horizontally Splitted after 3rd, 5th and 9th column : \n"+str(np.hsplit(F,(3,5,9))))


F is : 
[[69. 45. 61. 88. 60. 33. 46. 10. 84. 14. 44. 97.]
 [85. 79. 84. 62. 48.  7.  3. 14. 21. 60. 51. 18.]]
Horizontally Splitted in 3 : 
[array([[69., 45., 61., 88.],
       [85., 79., 84., 62.]]), array([[60., 33., 46., 10.],
       [48.,  7.,  3., 14.]]), array([[84., 14., 44., 97.],
       [21., 60., 51., 18.]])]
Horizontally Splitted after 3rd, 5th and 9th column : 
[array([[69., 45., 61.],
       [85., 79., 84.]]), array([[88., 60.],
       [62., 48.]]), array([[33., 46., 10., 84.],
       [ 7.,  3., 14., 21.]]), array([[14., 44., 97.],
       [60., 51., 18.]])]


In [69]:
# Copy and Views

G = np.arange(12)
H = G   # Does not create a copy

print("Id of G:  "+ str(id(G)))
print("Id of H:  "+ str(id(H)))
print("Is G is same as H? "+ str(G is H))

H.shape = 3,4
print("Shape of G is "+ str(G.shape))

H = G.view()     # Create a shallow copy
print("Id of G:  "+ str(id(G)))
print("Id of H:  "+ str(id(H)))
print("Is G is same as H? "+ str(G is H))

I = G.copy()     # A new array with new data in it

print("Id of G:  "+ str(id(G)))
print("Id of I:  "+ str(id(I)))
print("Is G is same as I? "+ str(G is I))

I[2,3] = 12

print("Id of G:  "+ str(G))
print("Id of I:  "+ str(I))


Id of G:  4514921888
Id of H:  4514921888
Is G is same as H? True
Shape of G is (3, 4)
Id of G:  4514921888
Id of H:  4514921168
Is G is same as H? False
Id of G:  4514921888
Id of I:  4514920608
Is G is same as I? False
Id of G:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Id of I:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 12]]
