# NumPy

## Features
 * **Vectorization** <br />
Vectorization is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently. 
Classic methods are: 
<ol>
    <li>Dot/Inner Products</li>
    Dot product is an algebraic operation in which two equal length vectors are being multiplied such that it produces a single number. Dot Product often called as inner product.
    <li>Outer Products</li>
    The tensor product of two coordinate vectors is termed as Outer product. Let’s consider two vectors a and b with dimension n x 1 and m x 1 then the outer product of the vector results in a rectangular matrix of n x m.
    <li>Element wise Product</li>
    Element-wise multiplication of two matrices is the algebraic operation in which each element of first matrix is multiplied by its corresponding element in the later matrix. Dimension of the matrices should be same.
</ol>
 * **Broadcasting**

In [11]:
# Inner Product
import time 
import numpy 
import array 
  
# 8 bytes size int 
a = array.array('q') 
for i in range(100000): 
    a.append(i); 
  
b = array.array('q') 
for i in range(100000, 200000): 
    b.append(i) 

# classic dot product of vectors implementation  
tic = time.process_time() 
dot = 0.0; 
  
for i in range(len(a)): 
      dot += a[i] * b[i] 
  
toc = time.process_time() 
  
print("dot_product = "+ str(dot)); 
print("Computation time = " + str(1000*(toc - tic )) + "ms") 
   
  
n_tic = time.process_time() 
n_dot_product = numpy.dot(a, b) 
n_toc = time.process_time() 
  
print("\nn_dot_product = "+str(n_dot_product)) 
print("Computation time = "+str(1000*(n_toc - n_tic ))+"ms") 

dot_product = 833323333350000.0
Computation time = 61.20999999996002ms

n_dot_product = 833323333350000
Computation time = 1.1859999999614956ms


In [12]:
# Outer product 
import time 
import numpy 
import array 
  
a = array.array('i') 
for i in range(200): 
    a.append(i); 
  
b = array.array('i') 
for i in range(200, 400): 
    b.append(i) 
  
# classic outer product of vectors implementation  
tic = time.process_time() 
outer_product = numpy.zeros((200, 200)) 
  
for i in range(len(a)): 
   for j in range(len(b)): 
      outer_product[i][j]= a[i]*b[j] 
  
toc = time.process_time() 
  
print("outer_product = "+ str(outer_product)); 
print("Computation time = "+str(1000*(toc - tic ))+"ms") 
   
n_tic = time.process_time() 
outer_product = numpy.outer(a, b) 
n_toc = time.process_time() 
  
print("outer_product = "+str(outer_product)); 
print("\nComputation time = "+str(1000*(n_toc - n_tic ))+"ms") 
  

outer_product = [[    0.     0.     0. ...     0.     0.     0.]
 [  200.   201.   202. ...   397.   398.   399.]
 [  400.   402.   404. ...   794.   796.   798.]
 ...
 [39400. 39597. 39794. ... 78209. 78406. 78603.]
 [39600. 39798. 39996. ... 78606. 78804. 79002.]
 [39800. 39999. 40198. ... 79003. 79202. 79401.]]
Computation time = 47.60999999996329ms
outer_product = [[    0     0     0 ...     0     0     0]
 [  200   201   202 ...   397   398   399]
 [  400   402   404 ...   794   796   798]
 ...
 [39400 39597 39794 ... 78209 78406 78603]
 [39600 39798 39996 ... 78606 78804 79002]
 [39800 39999 40198 ... 79003 79202 79401]]

Computation time = 0.3280000000813743ms


In [13]:
# Element-wise multiplication 
import time 
import numpy 
import array 
  
a = array.array('i') 
for i in range(50000): 
    a.append(i); 
  
b = array.array('i') 
for i in range(50000, 100000): 
    b.append(i) 
  
# classic element wise product of vectors implemetation  
vector = numpy.zeros((50000)) 
  
tic = time.process_time() 
  
for i in range(len(a)): 
      vector[i]= a[i]*b[i] 
  
toc = time.process_time() 
  
print("Element wise Product = "+ str(vector)); 
print("\nComputation time = "+str(1000*(toc - tic ))+"ms") 
   
  
n_tic = time.process_time() 
vector = numpy.multiply(a, b) 
n_toc = time.process_time() 
  
print("Element wise Product = "+str(vector)); 
print("\nComputation time = "+str(1000*(n_toc - n_tic ))+"ms") 

Element wise Product = [0.00000000e+00 5.00010000e+04 1.00004000e+05 ... 4.99955001e+09
 4.99970000e+09 4.99985000e+09]

Computation time = 38.85400000001482ms
Element wise Product = [        0     50001    100004 ... 704582713 704732708 704882705]

Computation time = 0.8339999999407155ms
