# Numpy Array

## 1.) Array Creation 

## 2.) Array Basics

## 3.) Basic Operations

## 4.) Indexing, Slicing and iterating


In [75]:
# Array creation

import numpy as np

a = np.array([10,20,30])
print ('a is : '+ str(a))

b = np.array([(15.1, 20.1, 30.9),(12.4,15.6, 45.3)])
print('b is : '+str(b))

x = np.arange(10).reshape(5,2)
print('x is : \n'+ str(x))

y = np.zeros(10).reshape(5,2)

print('y is : \n'+ str(y))

z = np.ones(10, dtype=np.int64).reshape(5,2)
print('z is : '+ str(z))

p = np.empty((2,3))
print('p is : \n'+ str(p))

# When arange is used with floating point arguments, 
# it is generally not possible to predict the number of elements obtained, 
# due to the finite floating point precision
q = np.arange(5,10,0.3)
print('q is : \n'+ str(q))

# 9 numbers from 0 to 2
r = np.linspace(0,2,9)
print('r is : \n'+ str(r))


a is : [10 20 30]
b is : [[15.1 20.1 30.9]
 [12.4 15.6 45.3]]
x is : 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y is : 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
z is : [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
p is : 
[[15.1 20.1 30.9]
 [12.4 15.6 45.3]]
q is : 
[5.  5.3 5.6 5.9 6.2 6.5 6.8 7.1 7.4 7.7 8.  8.3 8.6 8.9 9.2 9.5 9.8]
r is : 
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [72]:
# Array Basics

c = np.arange(20).reshape(5,2,2)
print("Array is : \n"+str(c))

print("Shape is : "+str(c.shape))
print("No. of dimentions are : "+ str(c.ndim))
print("Datatype is : "+ str(c.dtype.name))
print("Size is : "+ str(c.size))
print("Type is : "+ str(type(c)))


Array is : 
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
Shape is : (5, 2, 2)
No. of dimentions are : 3
Datatype is : int64
Size is : 20
Type is : <class 'numpy.ndarray'>


In [71]:
# Basic Operations

A = np.array([(1,2),(2,3)])
B = np.array([(3,2),(4,2)])

print("Element wise product: \n"+ str(A*B) )  # Element Wise Product


print("matrix product: \n"+ str(A @ B) )     # Matrix Product


print("Dot product: \n"+ str(A.dot(B) ) ) # dot Product



Element wise product: 
[[3 4]
 [8 6]]
matrix product: 
[[11  6]
 [18 10]]
Dot product: 
[[11  6]
 [18 10]]


In [85]:
C = np.ones((2,3), dtype = np.int64)
print("C is : \n"+ str(C ))

D = np.random.random((2,3))
print("D is : \n"+ str(D ))

D *= C

print("Updated D is : \n"+ str(D ))


C is : 
[[1 1 1]
 [1 1 1]]
D is : 
[[0.82683235 0.95214627 0.03678214]
 [0.51667226 0.62096994 0.75336647]]
D is : 
[[0.82683235 0.95214627 0.03678214]
 [0.51667226 0.62096994 0.75336647]]


In [99]:
# Unary Operations

E = np.random.random((2,3))
print("E is : \n"+ str( E ))

print("SUM is  : "+ str( E.sum() ))

print("MAX is  : "+ str( E.max() ))

print("MIN is  : "+ str( E.min() ))

F = np.arange(12).reshape(3,4)

print("F is : \n"+ str( F ))

print("SUM of axis 0 is : \n"+ str( F.sum(axis=0) ))

print("SUM of axis 1 is : \n"+ str( F.sum(axis=1) ))


print("CUMSUM of axis 1 is : \n"+ str( F.cumsum(axis=1) ))

E is : 
[[0.09949017 0.05472417 0.46358252]
 [0.91586275 0.430489   0.09680453]]
SUM is  : 2.060953143766248
MAX is  : 0.9158627501785234
MIN is  : 0.054724174098769174
F is : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
SUM of axis 0 is : 
[12 15 18 21]
SUM of axis 1 is : 
[ 6 22 38]
CUMSUM of axis 1 is : 
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [104]:
# Universal Functions (ufunc)

G = np.arange(4)

print("G is : \n"+str(G))

print("exponential is : \n"+str(np.exp(G))) # with base e

print("Square Root is : \n"+str(np.sqrt(G))) 

print("Mean is : \n"+str(np.mean(G))) 


G is : 
[0 1 2 3]
exponential is : 
[ 1.          2.71828183  7.3890561  20.08553692]
Square Root is : 
[0.         1.         1.41421356 1.73205081]
Square Root is : 
1.5


In [203]:
# Indexing, Slicing and iterating

H = np.arange(1,13,1).reshape(3,4)**2
print("H is : \n"+str(H))

print("Row 2 and 3 is : \n"+str(H[1:3])) # Since it uses indexes 

print("Column 2 and 3 is : \n"+str(H[:, 1:3 ])) 

print("Row and column 2 and 3 is : \n"+str(H[1:3, 1:3 ])) 

print("Last element is : \n"+str(H[-1, -1 ])) 


I = np.arange(1,25,1).reshape(6,4)

I[:7:2] = -1000  # equivalent to a[0:7:2] = -1000; from start to position 7, exclusive, set every 2nd element to -1000
print("I is : \n"+str(I))


H is : 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Row 2 and 3 is : 
[[ 25  36  49  64]
 [ 81 100 121 144]]
Column 2 and 3 is : 
[[  4   9]
 [ 36  49]
 [100 121]]
Row and column 2 and 3 is : 
[[ 36  49]
 [100 121]]
Last element is : 
144
I is : 
[[-1000 -1000 -1000 -1000]
 [    5     6     7     8]
 [-1000 -1000 -1000 -1000]
 [   13    14    15    16]
 [-1000 -1000 -1000 -1000]
 [   21    22    23    24]]


In [204]:
# Multidimentional Array

J = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

print("Shape is : \n"+str(J.shape))

print("Second Row is : \n"+str(J[1,...])) # same as J[1,:,:] or J[1]

print("Second Column is : \n"+str(J[...,1])) # same as c[:,:,1]


Shape is : 
(2, 2, 3)
Second Row is : 
[[100 101 102]
 [110 112 113]]
Second Column is : 
[[  1  12]
 [101 112]]
